# Generated by Django 4.1.3 on 2022-11-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_follows"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="follows",),
    ]
